package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 6:
        return new StopWatch_BehaviorDescriptor();
      case 1:
        return new Button_BehaviorDescriptor();
      case 5:
        return new SeparateControl_BehaviorDescriptor();
      case 7:
        return new UniversalControl_BehaviorDescriptor();
      case 0:
        return new AnalogDisplay_BehaviorDescriptor();
      case 3:
        return new DigitalDisplay_BehaviorDescriptor();
      case 4:
        return new Highlighting_BehaviorDescriptor();
      case 2:
        return new ColorRef_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"StopWatch.structure.AnalogDisplay", "StopWatch.structure.Button", "StopWatch.structure.ColorRef", "StopWatch.structure.DigitalDisplay", "StopWatch.structure.Highlighting", "StopWatch.structure.SeparateControl", "StopWatch.structure.StopWatch", "StopWatch.structure.UniversalControl"};
}
