package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Button_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Button_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Button";
  }
}
