package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ColorRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ColorRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.ColorRef";
  }
}
