package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Display_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Display_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Display";
  }
}
