package StopWatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Highlighting_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Highlighting_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.Highlighting";
  }
}
