package StopWatch.behavior;

/*Generated by MPS */


public class SeparateControl_BehaviorDescriptor extends ControlPanel_BehaviorDescriptor {
  public SeparateControl_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.SeparateControl";
  }
}
