package StopWatch.behavior;

/*Generated by MPS */


public class UniversalControl_BehaviorDescriptor extends ControlPanel_BehaviorDescriptor {
  public UniversalControl_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StopWatch.structure.UniversalControl";
  }
}
