package StopWatch.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new AnalogDisplay_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Button_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ColorRef_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new DigitalDisplay_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Highlighting_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new SeparateControl_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new StopWatch_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new UniversalControl_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0c, descriptor.getConceptFqName())) {
      case 0:
        if ("StopWatch.editor.ControlPanelPosition".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new ControlPanelPosition());
        }
        break;
      case 1:
        if ("StopWatch.editor.DisplayPrecision".equals(editorComponentId)) {
          return Collections.<ConceptEditorComponent>singletonList(new DisplayPrecision());
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"StopWatch.structure.AnalogDisplay", "StopWatch.structure.Button", "StopWatch.structure.ColorRef", "StopWatch.structure.DigitalDisplay", "StopWatch.structure.Highlighting", "StopWatch.structure.SeparateControl", "StopWatch.structure.StopWatch", "StopWatch.structure.UniversalControl"};
  private static String[] stringSwitchCases_xbvbvu_a0a0c = new String[]{"StopWatch.structure.ControlPanel", "StopWatch.structure.Display"};
}
