package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum ClockFaceNumbers {
  arable("arable", "arable"),
  roman("roman", "roman");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<ClockFaceNumbers> getConstants() {
    List<ClockFaceNumbers> list = ListSequence.fromList(new LinkedList<ClockFaceNumbers>());
    ListSequence.fromList(list).addElement(ClockFaceNumbers.arable);
    ListSequence.fromList(list).addElement(ClockFaceNumbers.roman);
    return list;
  }

  public static ClockFaceNumbers getDefault() {
    return ClockFaceNumbers.arable;
  }

  public static ClockFaceNumbers parseValue(String value) {
    if (value == null) {
      return ClockFaceNumbers.getDefault();
    }
    if (value.equals(ClockFaceNumbers.arable.getValueAsString())) {
      return ClockFaceNumbers.arable;
    }
    if (value.equals(ClockFaceNumbers.roman.getValueAsString())) {
      return ClockFaceNumbers.roman;
    }
    return ClockFaceNumbers.getDefault();
  }

  private String myValue;

  ClockFaceNumbers(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
