package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Material {
  metal("metal", "metal"),
  plastic("plastic", "plastic"),
  wooden("wooden", "wooden");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Material> getConstants() {
    List<Material> list = ListSequence.fromList(new LinkedList<Material>());
    ListSequence.fromList(list).addElement(Material.metal);
    ListSequence.fromList(list).addElement(Material.plastic);
    ListSequence.fromList(list).addElement(Material.wooden);
    return list;
  }

  public static Material getDefault() {
    return Material.metal;
  }

  public static Material parseValue(String value) {
    if (value == null) {
      return Material.getDefault();
    }
    if (value.equals(Material.metal.getValueAsString())) {
      return Material.metal;
    }
    if (value.equals(Material.plastic.getValueAsString())) {
      return Material.plastic;
    }
    if (value.equals(Material.wooden.getValueAsString())) {
      return Material.wooden;
    }
    return Material.getDefault();
  }

  private String myValue;

  Material(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
