package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Position {
  right("right", "right"),
  left("left", "left"),
  top("top", "top"),
  bottom("bottom", "bottom");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Position> getConstants() {
    List<Position> list = ListSequence.fromList(new LinkedList<Position>());
    ListSequence.fromList(list).addElement(Position.right);
    ListSequence.fromList(list).addElement(Position.left);
    ListSequence.fromList(list).addElement(Position.top);
    ListSequence.fromList(list).addElement(Position.bottom);
    return list;
  }

  public static Position getDefault() {
    return Position.right;
  }

  public static Position parseValue(String value) {
    if (value == null) {
      return Position.getDefault();
    }
    if (value.equals(Position.right.getValueAsString())) {
      return Position.right;
    }
    if (value.equals(Position.left.getValueAsString())) {
      return Position.left;
    }
    if (value.equals(Position.top.getValueAsString())) {
      return Position.top;
    }
    if (value.equals(Position.bottom.getValueAsString())) {
      return Position.bottom;
    }
    return Position.getDefault();
  }

  private String myValue;

  Position(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
