package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Shape {
  circle("circle", "circle"),
  square("square", "square"),
  hexagonal("hexagonal", "hexagonal");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Shape> getConstants() {
    List<Shape> list = ListSequence.fromList(new LinkedList<Shape>());
    ListSequence.fromList(list).addElement(Shape.circle);
    ListSequence.fromList(list).addElement(Shape.square);
    ListSequence.fromList(list).addElement(Shape.hexagonal);
    return list;
  }

  public static Shape getDefault() {
    return Shape.circle;
  }

  public static Shape parseValue(String value) {
    if (value == null) {
      return Shape.getDefault();
    }
    if (value.equals(Shape.circle.getValueAsString())) {
      return Shape.circle;
    }
    if (value.equals(Shape.square.getValueAsString())) {
      return Shape.square;
    }
    if (value.equals(Shape.hexagonal.getValueAsString())) {
      return Shape.hexagonal;
    }
    return Shape.getDefault();
  }

  private String myValue;

  Shape(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
