package StopWatch.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum TimeUnit {
  microsec("microsec", "microsec"),
  millisec("millisec", "millisec"),
  sec("sec", "sec");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<TimeUnit> getConstants() {
    List<TimeUnit> list = ListSequence.fromList(new LinkedList<TimeUnit>());
    ListSequence.fromList(list).addElement(TimeUnit.microsec);
    ListSequence.fromList(list).addElement(TimeUnit.millisec);
    ListSequence.fromList(list).addElement(TimeUnit.sec);
    return list;
  }

  public static TimeUnit getDefault() {
    return TimeUnit.sec;
  }

  public static TimeUnit parseValue(String value) {
    if (value == null) {
      return TimeUnit.getDefault();
    }
    if (value.equals(TimeUnit.microsec.getValueAsString())) {
      return TimeUnit.microsec;
    }
    if (value.equals(TimeUnit.millisec.getValueAsString())) {
      return TimeUnit.millisec;
    }
    if (value.equals(TimeUnit.sec.getValueAsString())) {
      return TimeUnit.sec;
    }
    return TimeUnit.getDefault();
  }

  private String myValue;

  TimeUnit(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
